services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dojo
    ports:
      - 5432:5432
    volumes:
      - dojo-data:/var/lib/postgresql/data

volumes:
  dojo-data: